// Necesitamos modificar las rutas de pruebas
### Recuperar todos los usuarios
GET http://localhost:1234/api/users

### Recuperar un usuario
GET http://localhost:1234/api/users/type/student

### Recuperar un usuario
GET http://localhost:1234/api/users/11

### Recuperar todas las propiedades
GET http://localhost:1234/api/properties

### Recuperar todos los arrendadores
GET http://localhost:1234/api/lessors

### Recuperar el arrendador
GET http://localhost:1234/api/lessors/19

### Iniciar sesión - Usuario correcto
POST http://localhost:1234/api/users/login
Content-Type: application/json

{
    "vchemail": "sherlyn@gmail.com",
    "vchpassword": "12345678"
}

### Iniciar sesión - Usuario correcto
POST http://localhost:1234/api/users/login
Content-Type: application/json

{
    "email": "sebastian.martinez7643@alumnos.udg.mx",
    "password": "12345678"
}

### Crear un usuario
POST http://localhost:1234/api/users
Content-Type: application/json

{
    "vchname": "Sherlyn",
    "vchpaternalsurname": "García",
    "vchmaternalsurname": "Romo",
    "vchemail": "marvelsml25@gmail.com",
    "vchpassword": "12345678",
    "dtbirthdate": "2002-11-13",
    "bnstatus": true,
    "vchimage": "https://res.cloudinary.com/dal8aivch/image/upload/v1712875535/students/v1smuum8jpcgvk1qppkw.png",
    "roleid": 1
}

### Crear un estudiante
POST http://localhost:1234/api/students
Content-Type: application/json

{
    "type_user": "student",
    "name": "Ana Isabel",
    "last_name": "Martínez López",
    "email": "ana.isable@gmail.com",
    "password": "12345678",
    "birthday": "2000-12-25T00:00:00.000Z",
    "status": "active",
    "code_student": 123456789,
    "university": "CUCEI"
}

### Crear un arrendador
POST http://localhost:1234/api/lessors
Content-Type: application/json

{
    "type_user": "lessor",
    "name": "Ana Isabel",
    "last_name": "Martínez López",
    "email": "ana.isable@gmail.com",
    "password": "12345",
    "birthday": "2000-12-25T00:00:00.000Z",
    "status": "inactive",
    "phone": "3320302203",
    "street": "Revolución",
    "zip": "45402",
    "suburb": "Cd.Aztlan",
    "municipality": "Tonalá",
    "state": "Jalisco"
}

### Crear un inmueble
POST http://localhost:1234/api/properties
Content-Type: application/json

{
    "lessor_id": "30",
    "type_house": "casa",
    "title": "Prueba de casa 1",
    "description": "Una casa muy bonita",
    "street": "Kukulcan #89",
    "zip": "45402",
    "suburb": "Rey Xolotl",
    "municipality": "Tonalá",
    "state": "Jalisco",
    "lat": 0.00,
    "lgn": 1.00,
    "availability": 1,
    "price": 1200.20
}

### Eliminar un usuario
DELETE http://localhost:1234/api/users/9

### Eliminar un estudiante
DELETE http://localhost:1234/api/students/11

### Eliminar un arrendador
DELETE http://localhost:1234/api/lessors/22

### Actualizar una parte del usuario
PATCH http://localhost:1234/api/users/8
Content-Type: application/json

{
    "email": "sherlyn@gmail.com",
    "password": "876543216"
}

### Actualizar una parte del lessor
PATCH  http://localhost:1234/api/lessors/3
Content-Type: application/json

{
    "street": "Av.Tonalá"
}

### Crear un usuario student
POST http://localhost:1234/api/students
Content-Type: application/json

{
    "birthday": "2002-02-11",
    "code_student": 220976438,
    "email": "sebastian.martinez7643@alumnos.udg.mx",
    "last_name": "Martínez López",
    "name": "Sebastián",
    "password": "Ultron021122*",
    "status": "active",
    "type_user": "student",
    "university": "Centro Universitario de Ciencias Exactas e Ingenierías (CUCEI)"
}